on:
  push:
    branches: [master, main]
    paths:
      - 'index.Rmd'
      - '_redirects'
      - '.github/workflows/render-index.yaml'
  pull_request:
    branches: [master, main]
    paths:
      - 'index.Rmd'
      - '_redirects'
      - '.github/workflows/render-index.yaml'
  workflow_dispatch:

name: Render homepage

jobs:
  render:
    name: Render homepage
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          # checkout PR branch or push branch
          ref: ${{ github.head_ref || github.ref }}
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
        
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with: 
          pandoc-version: '2.15'

      - uses: r-lib/actions/setup-renv@v2
        env:
          RENV_CONFIG_REPOS_OVERRIDE: ${{ env.RSPM }}
      
      - name: Render Rmarkdown files
        run: rmarkdown::render("index.Rmd")
        shell: Rscript {0}
        
      - name: Git status
        run: git status
      
      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add index.html
          git commit -m 'Re-build index page'
          git pull -r
          git push
