on:
  push:
    branches: [gha-build]
    paths:
      - 'index.Rmd'
      - '_redirects'
      - '.github/workflows/render-index.yaml'

name: Render homepage

jobs:
  render:
    name: Render homepage
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      
      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v1
      
      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-
      
      - name: Install packages
        run: | 
          install.packages("renv")'
          renv::restore()'
        shell: Rscript {0}
      
      - name: Render Rmarkdown files
        run: rmarkdown::render("index.Rmd")
        shell: Rscript {0}
      
      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add index.html
          git commit -m 'Re-build index page'
          git push origin ${{ github.head_ref }} 
